"""device_token table and message.external_id

Revision ID: 40bb0fcad8c1
Revises: bae39a06bae0
Create Date: 2026-07-18 17:57:06.143233

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "40bb0fcad8c1"
down_revision: str | None = "bae39a06bae0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_token",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_token")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_device_token_token_hash")),
    )
    op.add_column("message", sa.Column("external_id", sa.String(length=500), nullable=True))
    # (autogenerate wanted to drop ix_message_content_fts — it just can't
    # model functional indexes; the index stays.)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "external_id")
    op.drop_table("device_token")
    # ### end Alembic commands ###
