"""job_run table, conversation.summarized_at, message FTS index

Revision ID: bae39a06bae0
Revises: ca0f4e17cc20
Create Date: 2026-07-18 17:29:42.123683

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "bae39a06bae0"
down_revision: str | None = "ca0f4e17cc20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_run",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("running", "success", "error", "skipped", name="job_status"),
            server_default="running",
            nullable=False,
        ),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_run")),
    )
    op.create_index("ix_job_run_name_started_at", "job_run", ["name", "started_at"], unique=False)
    op.add_column(
        "conversation", sa.Column("summarized_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###
    # Keyword half of hybrid search (the vector half uses the HNSW index).
    op.execute(
        "CREATE INDEX ix_message_content_fts ON message USING gin (to_tsvector('english', content))"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_message_content_fts")
    op.drop_column("conversation", "summarized_at")
    op.drop_index("ix_job_run_name_started_at", table_name="job_run")
    op.drop_table("job_run")
    op.execute("DROP TYPE IF EXISTS job_status")
    # ### end Alembic commands ###
