"""provider_key spend precision and spend_month

Revision ID: ca0f4e17cc20
Revises: f1992296b15f
Create Date: 2026-07-16 18:00:18.038505

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ca0f4e17cc20"
down_revision: str | None = "f1992296b15f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("provider_key", sa.Column("spend_month", sa.Date(), nullable=True))
    op.alter_column(
        "provider_key",
        "spend_usd",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=10, scale=6),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "provider_key",
        "spend_usd",
        existing_type=sa.Numeric(precision=10, scale=6),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_column("provider_key", "spend_month")
    # ### end Alembic commands ###
