"""assistant layer: suggestion, review, extraction bookkeeping

Revision ID: f926188861d1
Revises: 40bb0fcad8c1
Create Date: 2026-07-19 08:16:21.891106

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f926188861d1"
down_revision: str | None = "40bb0fcad8c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review")),
        sa.UniqueConstraint("period_start", name=op.f("uq_review_period_start")),
    )
    op.create_table(
        "suggestion",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("kind", sa.String(length=50), server_default="loose_end", nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.id"],
            name=op.f("fk_suggestion_conversation_id_conversation"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suggestion")),
        sa.UniqueConstraint("conversation_id", name=op.f("uq_suggestion_conversation_id")),
    )
    op.add_column(
        "conversation", sa.Column("tasks_extracted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "conversation", sa.Column("loose_end_checked_at", sa.DateTime(timezone=True), nullable=True)
    )
    # (autogenerate wants to drop ix_message_content_fts because Alembic can't
    # model functional indexes — removed by hand, as in earlier migrations.)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversation", "loose_end_checked_at")
    op.drop_column("conversation", "tasks_extracted_at")
    op.drop_table("suggestion")
    op.drop_table("review")
    # ### end Alembic commands ###
